export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  ABOUT: "/about",
  SERVICE: "/services",
  BLOGS: "/blogs",
  CONTACT: "/contact",
  PORTFOLIO: "/portfolio",
  PACKAGES: "/packages",
  TESTIMONIALS: "/testimonials",
  PRIVACY_POLICY: "/privacy-policy",
  TERMS_CONDITION: "/terms-and-condition",
  THANK_YOU: "/thank-you",
  SERVICE_WEBSITE: "/services/website-development",
  SERVICE_GRAPHICS: "/services/graphic-design",
  SERVICE_ANIMATION: "/services/animation",
  SERVICE_SOCIAL: "/services/social-media-marketing",
  SERVICE_BRANDING: "/services/branding-and-strategy",
  SERVICE_STREAMERS: "/services/streamers-templates",
  SERVICE_APP: "/services/app-development",
  SERVICE_SEO: "/services/seo",
  SERVICE_EMAIL: "/services/email-marketing",
  SERVICE_GOOGLE: "/services/google-ads",
  POST_ADD: "/add-post",
  ADMIN: "/admin",
  PROFILE: "/profile",
  STREAMERS: "/services/streamers-templates",
};
